compatibility_date = "2023-12-01"
name = "cloudflare-docker-proxy"

[dev]
ip = "0.0.0.0"
local_protocol = "http"
port = 8787

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.glxycl.top", custom_domain = true },
  { pattern = "quay.glxycl.top", custom_domain = true },
  { pattern = "gcr.glxycl.top", custom_domain = true },
  { pattern = "k8s-gcr.glxycl.top", custom_domain = true },
  { pattern = "k8s.glxycl.top", custom_domain = true },
  { pattern = "ghcr.glxycl.top", custom_domain = true },
  { pattern = "cloudsmith.glxycl.top", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.glxycl.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
